// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Party.Model;

#nullable disable

namespace Party.Migrations
{
    [DbContext(typeof(PartyContext))]
    partial class PartyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Party.Model.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartyRequestRequestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartyRequestRequestId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Party.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Party.Model.PartyRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Applicant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicantPN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Baloons")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaloonsWithHelium")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthdayPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BirthdayPersonAge")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Partydate")
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.HasIndex("OrderId");

                    b.ToTable("party_request");
                });

            modelBuilder.Entity("Party.Model.Guest", b =>
                {
                    b.HasOne("Party.Model.PartyRequest", null)
                        .WithMany("Guests")
                        .HasForeignKey("PartyRequestRequestId");
                });

            modelBuilder.Entity("Party.Model.PartyRequest", b =>
                {
                    b.HasOne("Party.Model.Order", null)
                        .WithMany("PartyRequest")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Party.Model.Order", b =>
                {
                    b.Navigation("PartyRequest");
                });

            modelBuilder.Entity("Party.Model.PartyRequest", b =>
                {
                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
